version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-vollmed
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
        "--sql_mode=STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION",
      ]
    restart: on-failure
    env_file: .env
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${HOST_MYSQL_PORT}:3306"
    deploy:
      resources:
        limits:
          memory: 2048M
    networks:
      - internal-network

volumes:
  mysql-data:

networks:
  internal-network:
    driver: bridge